output_dir: ~/scratch/experiments/

dataset:
  class: FB15k237Inductive
  path: ~/kg-datasets/
  version: {{ version }}

task:
  class: InductiveKnowledgeGraphCompletion
  model:
    class: AStarNet
    base_layer:
      class: NBFNetConv
      input_dim: 32
      output_dim: 32
      query_input_dim: 32
      message_func: distmult
      aggregate_func: sum
      layer_norm: yes
      dependent: yes
    num_layer: 6
    short_cut: yes
    node_ratio: 0.5
    test_node_ratio: 1
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 64

train:
  num_epoch: 20

metric: mrr