output_dir: ~/experiments/

dataset:
  class: OGBLWikiKG2
  path: ~/datasets/knowledge_graphs/

task:
  class: KnowledgeGraphCompletionOGB
  model:
    class: AStarNet
    base_layer:
      class: NBFNetConv
      input_dim: 32
      output_dim: 32
      query_input_dim: 32
      message_func: distmult
      aggregate_func: sum
      layer_norm: yes
      dependent: yes
    num_layer: 6
    indicator_func: ppr
    short_cut: yes
    node_ratio: 0.002
    test_node_ratio: 0.01
    break_tie: yes
    edge_dropout: 0.2
  criterion: bce
  num_negative: 1048576
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32
  log_interval: 10

train:
  num_epoch: 50
  batch_per_epoch: 400

fast_test: 5000

metric: mrr